Vagrant.configure("2") do |config|

  config.vm.define "Server" do |server|

    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "dohanyanS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/home/vagrant/p2"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "dohanyanS"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/k3s_server.sh"
  end
end
