apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitlab

  source:
    repoURL: http://172.187.162.207/root/argocd
    targetRevision: HEAD
    path: bonus/confs/charts

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
