apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app1-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: app1-html
          hostPath:
            path: /home/vagrant/p2/confs/app1/app
            type: Directory
