Vagrant.configure("2") do |config|

  config.vm.define "Server" do |server|

    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "dohanyanS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/home/vagrant/p1"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "dohanyan"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/k3s_server.sh"
  end

  config.vm.define "Worker" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "dohanyanSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/home/vagrant/p1"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "arakhurs"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/k3s_worker.sh"
  end

end
