name: Deploy Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string
        default: "0"

      msg:
        description: 'Special msg in web'
        required: true
        type: string
        default: "Hello, World!"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image with message
        run: |
          docker build \
            -t dohanyan/devops-site:${{ github.event.inputs.version }} \
            --build-arg MESSAGE="${{ github.event.inputs.msg }}" \
            ./p3/confs/
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Load image from tar and push
        run: |
          docker push  dohanyan/devops-site:${{ github.event.inputs.version }}
